### ISSUE TITLE
Conflicting cross-version in SBT 1.5.5, however it works in 1.5.4

### ISSUE THREAD

**Issue by mvillafuertem** [com-lihaoyi/Ammonite#1197]
Hi there,

I am getting this errors after update sbt to 1.5.5. 

Thanks

```
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: com.lihaoyi:sourcecode, com.lihaoyi:fansi, com.lihaoyi:pprint
2973
[error] 	at scala.sys.package$.error(package.scala:30)
2974
[error] 	at sbt.librarymanagement.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:39)
2975
[error] 	at sbt.librarymanagement.ConflictWarning$.apply(ConflictWarning.scala:19)
2976
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$71(Defaults.scala:3194)
2977
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2978
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2979
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
2980
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
2981
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
2982
[error] 	at sbt.Execute.work(Execute.scala:291)
2983
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
2984
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
2985
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
2986
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2987
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2988
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2989
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2990
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2991
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
2992
[error] (script / update) Conflicting cross-version suffixes in: com.lihaoyi:sourcecode, com.lihaoyi:fansi, com.lihaoyi:pprint

```

**Comment by dispalt** [comment]
I think it's related to this fix https://github.com/sbt/librarymanagement/pull/383, I excluded the `_3` version (im on 2.13.x) as a workaround.  I have no idea if it's published correctly though:

```
"com.lihaoyi" % "ammonite" % Version.Ammonite cross CrossVersion.full exclude ("com.lihaoyi", "sourcecode_3") exclude ("com.lihaoyi", "fansi_3") exclude ("com.lihaoyi", "pprint_3")
```

**Comment by nbauernfeind** [comment]
The artifact(s) are published incorrectly and are explicitly depending on scala_3 versions of things in scala 2.13.

See: https://search.maven.org/artifact/com.lihaoyi/ammonite-cross-23-util_2.13/2.4.0-19-f4790b61/jar

I don't know if that is an issue in addition to the above, or if they are separate issues. I've filed #1214 which makes it clear that the generated pom is incorrect -- and is not `sbt` specific.

**Comment by lihaoyi** [comment]
@alexarchambault probably knows the most about Ammonite and Scala3

**Comment by mvillafuertem** [comment]
Hi @alexarchambault I keep getting the same error, I have created a simple project to help reproduce the error.

https://github.com/mvillafuertem/amm-error

I have tried @dispalt's suggestion using exclude, but I get this error. Some hint? Thanks
```
Ammonite REPL & Script-Runner, 2.4.1
Exception in thread "main" java.lang.NullPointerException
        at dotty.tools.dotc.core.Types$TypeBounds$.empty(Types.scala:4999)
        at dotty.tools.dotc.core.Definitions.enterBinaryAlias(Definitions.scala:154)
        at dotty.tools.dotc.core.Definitions.andType(Definitions.scala:441)
        at dotty.tools.dotc.ast.untpd$.makeAndType(untpd.scala:503)
        at dotty.tools.dotc.parsing.Parsers$Parser.withTypeRest(Parsers.scala:1548)
        at dotty.tools.dotc.parsing.Parsers$Parser.withType(Parsers.scala:1537)
        at dotty.tools.dotc.parsing.Parsers$Parser.refinedType(Parsers.scala:1524)
        at dotty.tools.dotc.parsing.Parsers$Parser.infixType(Parsers.scala:1513)
        at dotty.tools.dotc.parsing.Parsers$Parser.typ(Parsers.scala:1449)
        at dotty.tools.dotc.parsing.Parsers$Parser.argType$1(Parsers.scala:1720)
        at dotty.tools.dotc.parsing.Parsers$Parser.argTypes$$anonfun$3(Parsers.scala:1747)
        at dotty.tools.dotc.parsing.Parsers$Parser.tokenSeparated(Parsers.scala:555)
        at dotty.tools.dotc.parsing.Parsers$Parser.commaSeparated(Parsers.scala:563)
        at dotty.tools.dotc.parsing.Parsers$Parser.argTypes(Parsers.scala:1747)
        at dotty.tools.dotc.parsing.Parsers$Parser.typeArgs$$anonfun$1(Parsers.scala:1776)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:533)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBrackets(Parsers.scala:537)
        at dotty.tools.dotc.parsing.Parsers$Parser.typeArgs(Parsers.scala:1776)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleTypeRest(Parsers.scala:1656)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleType1(Parsers.scala:1649)
        at dotty.tools.dotc.parsing.Parsers$Parser.simpleType(Parsers.scala:1619)
        at dotty.tools.dotc.parsing.Parsers$Parser.annotType(Parsers.scala:1553)
        at dotty.tools.dotc.parsing.Parsers$Parser.withType(Parsers.scala:1537)
        at dotty.tools.dotc.parsing.Parsers$Parser.refinedType(Parsers.scala:1524)
        at dotty.tools.dotc.parsing.Parsers$Parser.infixType(Parsers.scala:1513)
        at dotty.tools.dotc.parsing.Parsers$Parser.typ(Parsers.scala:1449)
        at dotty.tools.dotc.parsing.Parsers$Parser.toplevelTyp(Parsers.scala:1323)
        at dotty.tools.dotc.parsing.Parsers$Parser.typedOpt(Parsers.scala:1820)
        at dotty.tools.dotc.parsing.Parsers$Parser.$anonfun$22(Parsers.scala:3355)
        at dotty.tools.dotc.parsing.Parsers$Parser.fromWithinReturnType(Parsers.scala:386)
        at dotty.tools.dotc.parsing.Parsers$Parser.defDefOrDcl(Parsers.scala:3355)
        at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:3251)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq$$anonfun$1(Parsers.scala:3879)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:477)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateStatSeq(Parsers.scala:3887)
        at dotty.tools.dotc.parsing.Parsers$Parser.$anonfun$33(Parsers.scala:3774)
        at dotty.tools.dotc.parsing.Parsers$Parser.enclosed(Parsers.scala:533)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBraces(Parsers.scala:536)
        at dotty.tools.dotc.parsing.Parsers$Parser.inBracesOrIndented(Parsers.scala:547)
        at dotty.tools.dotc.parsing.Parsers$Parser.inDefScopeBraces(Parsers.scala:550)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateBody(Parsers.scala:3774)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateBodyOpt(Parsers.scala:3767)
        at dotty.tools.dotc.parsing.Parsers$Parser.template(Parsers.scala:3744)
        at dotty.tools.dotc.parsing.Parsers$Parser.templateOpt(Parsers.scala:3752)
        at dotty.tools.dotc.parsing.Parsers$Parser.objectDef(Parsers.scala:3506)
        at dotty.tools.dotc.parsing.Parsers$Parser.tmplDef(Parsers.scala:3465)
        at dotty.tools.dotc.parsing.Parsers$Parser.defOrDcl(Parsers.scala:3257)
        at ammonite.compiler.DottyParser.localDef(DottyParser.scala:39)
        at ammonite.compiler.DottyParser.blockStatSeq$$anonfun$1(DottyParser.scala:63)
        at dotty.tools.dotc.parsing.Parsers$Parser.checkNoEscapingPlaceholders(Parsers.scala:477)
        at ammonite.compiler.DottyParser.blockStatSeq(DottyParser.scala:69)
        at ammonite.compiler.Parsers.parseStats(Parsers.scala:29)
        at ammonite.compiler.Parsers.$anonfun$2(Parsers.scala:84)
        at dotty.tools.dotc.reporting.Reporter.withIncompleteHandler(Reporter.scala:94)
        at ammonite.compiler.Parsers.doSplit(Parsers.scala:85)
        at ammonite.compiler.Parsers.$anonfun$9(Parsers.scala:260)
        at scala.collection.immutable.Vector1.map(Vector.scala:1872)
        at scala.collection.immutable.Vector1.map(Vector.scala:375)
        at ammonite.compiler.Parsers.scriptBlocksWithStartIndices(Parsers.scala:279)
        at ammonite.compiler.Parsers.splitScript(Parsers.scala:238)
        at ammonite.interp.Interpreter.splittedScript$lzycompute$1(Interpreter.scala:391)
        at ammonite.interp.Interpreter.splittedScript$1(Interpreter.scala:389)
        at ammonite.interp.Interpreter.processModule(Interpreter.scala:396)
        at ammonite.main.Scripts$.$anonfun$runScript$1(Scripts.scala:32)
        at ammonite.util.Res$Success.flatMap(Res.scala:62)
        at ammonite.main.Scripts$.runScript(Scripts.scala:28)
        at ammonite.Main.runScript(Main.scala:250)
        at ammonite.MainRunner.$anonfun$runScript$1(Main.scala:447)
        at ammonite.MainRunner.watchLoop(Main.scala:433)
        at ammonite.MainRunner.runScript(Main.scala:447)
        at ammonite.Main$.main0(Main.scala:355)
        at ammonite.Main$.main(Main.scala:281)
        at ammonite.Main.main(Main.scala)

```
