### ISSUE TITLE
Use of deprecated `Thread.stop` prevents working on Java 20+

### ISSUE THREAD

**Issue by Jengamon** [com-lihaoyi/Ammonite#1379]
Steps to reproduce:
1. Install a JDK/JRE for Java 20 or later.
2. Open an Ammonite REPL using that JDK/JRE (using Scala 3, but that isn't too relevant maybe)
3. Run the line `while true do ()` (Scala 3)
4. Attempt to Ctrl-C
5. You should see
```
Exception in thread "SIGINT handler" java.lang.UnsupportedOperationException
        at java.base/java.lang.Thread.stop(Thread.java:1705)
        at ammonite.repl.Repl.$anonfun$action$5(Repl.scala:191)
        at ammonite.repl.Signaller$$anon$1.handle(Signaller.scala:21)
        at jdk.unsupported/sun.misc.Signal$InternalMiscHandler.handle(Signal.java:198)
        at java.base/jdk.internal.misc.Signal$1.run(Signal.java:218)
        at java.base/java.lang.Thread.run(Thread.java:1623)
```
because in Java 20 (https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/Thread.html#stop()) the function has been "removed" and apparently should be replaced with `Thread.interrupt` and interruption checking/allowing on the execution thread.

The problematic line seems to be here:
https://github.com/com-lihaoyi/Ammonite/blob/084f7f4e6f6bac561f4940a053b84a1e4f39e96e/amm/repl/src/main/scala/ammonite/repl/Repl.scala#L191

Expected behavior:
I expected to be able to interrupt long running programs, which was one of the advertised benefits of Ammonite-REPL.

Environment:
Ammonite: 3.0.0-M0-53-084f7f4e
Scala: 3.3.1
Java: 20

**Comment by alexarchambault** [comment]
A problem here, IIUC, is that there's no real substitute for `Thread.stop` when users want to stop code like `while (true) {}` (or any code that keeps the CPU busy doing computation, rather than waiting for I/O and the like).

**Comment by rednaxelafx** [comment]
Bypassing the public Java API to reach into the JVM for the `stop()` implementation isn't going to be portable, or supported in the long run. There is indeed no replacement for the `stop()` due to its semantics being problematic in the first place (i.e. skips proper unwinding of the stack)

The thing about being a REPL though is that you sort of have control over the compiler, at least for the part that was entered through the REPL. It might be possible to artificially add in a "blackhole"-style empty method at the backedges of all the loops to allow interrupts to have an anchor point to deliver to.

**Comment by Jengamon** [comment]
...SecurityManager is also on track for removal https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/SecurityManager.html

**Comment by lefou** [comment]
> ...SecurityManager is also on track for removal https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/SecurityManager.html

Looks like a secret conspiracy to make threads immortal. 🤣
